declare const functions: {
    Client: {
        login: (host: string, key: string, callback: any) => void;
        fastLogin: (host: string, key: string) => void;
        getServerName: typeof import("./client/methods/serverInfo/getServerName").default;
        getAllServers: typeof import("./client/methods/serverInfo/getAllServers").default;
        getServerInfo: typeof import("./client/methods/serverInfo/getServerInfo").default;
        getCPU: typeof import("./client/methods/serverLimits/getCPU").default;
        getMemory: typeof import("./client/methods/serverLimits/getMemory").default;
        getDisk: typeof import("./client/methods/serverLimits/getDisk").default;
        isOwner: typeof import("./client/methods/serverInfo/isOwner").default;
        getIPAlias: typeof import("./client/methods/serverInfo/getServerIPAlias").default;
        getServerPort: typeof import("./client/methods/serverInfo/getServerPort").default;
        getNummericIP: typeof import("./client/methods/serverInfo/getNummericIP").default;
        getServerStatus: typeof import("./client/methods/serverInfo/getServerStatus").default;
        getCPUUsage: typeof import("./client/methods/serverUsage/getCPUUsage").default;
        getMemoryUsage: (serverId: string) => any;
        getDiskUsage: typeof import("./client/methods/serverUsage/getDiskUsage").default;
        createBackup: typeof import("./client/methods/backups/createBackup").default;
        deleteBackup: typeof import("./client/methods/backups/deleteBackup").default;
        getAllBackups: typeof import("./client/methods/backups/getAllBackups").default;
        getBackupInfo: typeof import("./client/methods/backups/getBackupInfo").default;
        startServer: typeof import("./client/methods/serverActions/startServer").default;
        stopServer: typeof import("./client/methods/serverActions/stopServer").default;
        killServer: typeof import("./client/methods/serverActions/killServer").default;
        restartServer: typeof import("./client/methods/serverActions/restartServer").default;
        sendCommand: typeof import("./client/methods/serverActions/sendCommand").default;
        post: typeof import("./client/methods/post").default;
        get: typeof import("./client/methods/get").default;
        put: typeof import("./client/methods/put").default;
        delete: typeof import("./client/methods/delete").default;
    };
    Admin: {
        login: (host: string, key: string, callback: any) => void;
        fastLogin: (host: string, key: string) => void;
        getUserInfo: typeof import("./application/methods/users/getUserInfo").default;
        getAllUsers: typeof import("./application/methods/users/getAllUsers").default;
        updateUser: typeof import("./application/methods/users/updateUser").default;
        createUser: typeof import("./application/methods/users/createUser").default;
        deleteUser: typeof import("./application/methods/users/deleteUser").default;
        getServerInfo: typeof import("./application/methods/servers/getServerInfo").default;
        getAllServers: typeof import("./application/methods/servers/getAllServers").default;
        createServer: typeof import("./application/methods/servers/createServer").default;
        suspendServer: typeof import("./application/methods/servers/suspendServer").default;
        unsuspendServer: typeof import("./application/methods/servers/unsuspendServer").default;
        updateBuild: typeof import("./application/methods/servers/updateBuild").default;
        updateDetails: typeof import("./application/methods/servers/updateDetails").default;
        deleteServer: typeof import("./application/methods/servers/deleteServer").default;
        getNodeInfo: typeof import("./application/methods/nodes/getNodeInfo").default;
        getAllNodes: typeof import("./application/methods/nodes/getAllNodes").default;
        createNode: typeof import("./application/methods/nodes/createNode").default;
        createAllocation: typeof import("./application/methods/allocations/createAllocation").default;
        deleteNode: typeof import("./application/methods/nodes/deleteNode").default;
        getAllDatabases: typeof import("./application/methods/databases/getAllDatabases").default;
        getDatabaseInfo: typeof import("./application/methods/databases/getDatabaseInfo").default;
        createDatabase: typeof import("./application/methods/databases/createDatabase").default;
        resetDatabasePassword: typeof import("./application/methods/databases/resetDatabasePassword").default;
        deleteDatabase: typeof import("./application/methods/databases/deleteDatabase").default;
        getAllAllocations: typeof import("./application/methods/allocations/getAllAllocations").default;
        deleteAllocation: typeof import("./application/methods/allocations/deleteAllocation").default;
        post: typeof import("./application/methods/post").default;
        get: typeof import("./application/methods/get").default;
        put: typeof import("./application/methods/put").default;
        delete: typeof import("./application/methods/delete").default;
    };
};
export = functions;
